// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus():Promise<boolean>;

export function StartServer():Promise<string>;

export function StopServer():Promise<string>;
